name: build-usrp-server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:ettusresearch/uhd
        sudo apt-get update
        sudo apt-get install libboost-all-dev libzmq3-dev fftw3-dev rapidjson-dev libuhd-dev libuhd3.15.0 uhd-host

    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
